### ISSUE TITLE
LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Jick9536** [Protryon/misiri_driver#2]
SO: Windows 10 Home. 
Node js version: v12.14.1
Device Model: MSR605X

C:\Users\jick9\Desktop\t-m\misiri_driver-master>node index.js
1 interfaces found.
C:\Users\jick9\Desktop\t-m\misiri_driver-master\node_modules\usb\usb.js:322
        return this.device.__isKernelDriverActive(this.id)
                           ^
Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Interface.isKernelDriverActive (C:\Users\jick9\Desktop\t-m\misiri_driver-master\node_modules\usb\usb.js:322:21)
    at connectToDevice (C:\Users\jick9\Desktop\t-m\misiri_driver-master\index.js:199:19)
    at Object.<anonymous> (C:\Users\jick9\Desktop\t-m\misiri_driver-master\index.js:209:31)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -12
}

C:\Users\jick9\Desktop\t-m\misiri_driver-master>

**Comment by edwardh5** [comment]
Seems to be a problem with the usb library. Saw something similar on OSX. Ended up running in Ubuntu 19.10 and didn't have that issue.
